package org.earnlumens.mediastore.domain.media.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Server-side record of an upload initiated via {@code POST /api/uploads/init}.
 * <p>
 * Binds the {@code uploadId} handed to the client to the exact R2 key,
 * content type and expected size generated by the server, so that
 * {@code /finalize} can verify the client is finalizing the upload it was
 * authorized for (and not an arbitrary r2Key). Also carries the S3 multipart
 * upload id for large files so {@code /complete} and {@code /abort} can
 * operate on it.
 */
@Document(collection = "upload_sessions")
public class UploadSession {

    public enum Status { PENDING, COMPLETED, ABORTED }

    @Id
    private String id; // the uploadId handed to the client

    @Indexed
    private String tenantId;

    private String userId;

    @Indexed
    private String entryId;

    /** MediaKind name: FULL | THUMBNAIL | PREVIEW */
    private String kind;

    private String r2Key;

    private String contentType;

    private String fileName;

    private Long expectedSizeBytes;

    /** True when the upload uses S3 multipart (large files). */
    private boolean multipart;

    /** S3/R2 multipart upload id (only when multipart=true). */
    private String s3UploadId;

    private Long partSizeBytes;

    private Integer totalParts;

    private Status status = Status.PENDING;

    /** Asset id persisted at finalize time (idempotency). */
    private String assetId;

    @Indexed
    private LocalDateTime createdAt = LocalDateTime.now();

    private LocalDateTime completedAt;

    // ─── Getters / setters ──────────────────────────────────────

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getTenantId() { return tenantId; }
    public void setTenantId(String tenantId) { this.tenantId = tenantId; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public String getEntryId() { return entryId; }
    public void setEntryId(String entryId) { this.entryId = entryId; }

    public String getKind() { return kind; }
    public void setKind(String kind) { this.kind = kind; }

    public String getR2Key() { return r2Key; }
    public void setR2Key(String r2Key) { this.r2Key = r2Key; }

    public String getContentType() { return contentType; }
    public void setContentType(String contentType) { this.contentType = contentType; }

    public String getFileName() { return fileName; }
    public void setFileName(String fileName) { this.fileName = fileName; }

    public Long getExpectedSizeBytes() { return expectedSizeBytes; }
    public void setExpectedSizeBytes(Long expectedSizeBytes) { this.expectedSizeBytes = expectedSizeBytes; }

    public boolean isMultipart() { return multipart; }
    public void setMultipart(boolean multipart) { this.multipart = multipart; }

    public String getS3UploadId() { return s3UploadId; }
    public void setS3UploadId(String s3UploadId) { this.s3UploadId = s3UploadId; }

    public Long getPartSizeBytes() { return partSizeBytes; }
    public void setPartSizeBytes(Long partSizeBytes) { this.partSizeBytes = partSizeBytes; }

    public Integer getTotalParts() { return totalParts; }
    public void setTotalParts(Integer totalParts) { this.totalParts = totalParts; }

    public Status getStatus() { return status; }
    public void setStatus(Status status) { this.status = status; }

    public String getAssetId() { return assetId; }
    public void setAssetId(String assetId) { this.assetId = assetId; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getCompletedAt() { return completedAt; }
    public void setCompletedAt(LocalDateTime completedAt) { this.completedAt = completedAt; }
}
